doc: update readme.md.  the sample code is err
if you not , you can see 

```
SyntaxError: await is only valid in async function
```

by the way ，i add two options(packageFile and upgrade) so that easier to understand it